name: final_assignment
channels:
  - pytorch
dependencies:
  - python=3.8 
  - pytorch=1.10 
  - cudatoolkit=11.3 
  - torchvision
  - pip 
  - pandas
  - pyarrow
  - ipykernel
  - cudnn # For paddleocr, missing from their environments
  - pip:
    - trdg # TextRecognitionDataGenerator, for generating synthetic data samples 
    - nlpashto # Word segmentation
    - click
    - paddlepaddle-gpu # For GPU training
    - paddleocr # For training model
    - albumentations # For paddleocr, missing from their requirements